mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('all_tasks/', views.all_tasks, name='all_tasks'),
    path('<int:task_id>/', views.task, name='task'),
    path('create_task/', views.create_task, name='create_task'),
    path('<int:task_id>/delete', views.delete_task, name='delete_task'),
]

polls/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    description = models.CharField(max_length=500)
    
    def __str__(self):
        return self.title

polls/views.py
from django.db import reset_queries
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.utils import timezone

from .models import Task

# Create your views here.
def index(request):
    return HttpResponse("Welcome to my Project")

def all_tasks(request):
    '''
    Return a dictionary with all tasks
    '''
    if request.method == 'GET':
        tasks_title = Task.objects.all()
        return render(request, 'polls/all_tasks.html', {'tasks_title': tasks_title})

def task(request, task_id):
    '''
    Return an specific task by its title
    '''
    if request.method == 'GET':
        task = get_object_or_404(Task, pk = task_id)
        return render(request, 'polls/task.html', {'task': task})

def create_task(request):
    '''
    Create a task
    '''
    if request.method == 'POST':
        task = Task.objects.create(title=request.POST['title'], pub_date=timezone.now(), description=request.POST['description'])
        return render(request, 'polls/task.html', {'task': task})

def delete_task(request, task_id):
    '''
    Delete a task
    '''
    if request.method == 'POST':
        print()
        task = get_object_or_404(Task, pk = request.POST['task_id'])
        task.delete()

        tasks_title = Task.objects.all()
        return render(request, 'polls/all_tasks.html', {'tasks_title': tasks_title})

polls/templates/polls/all_tasks.html
<!DOCTYPE html>
<html>
    <body>
        {% if tasks_title %}
            <ul>
            {% for task in tasks_title %}
                <li><a href="{% url 'polls:task' task.id  %}">{{ task.title }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>Nenhuma task existente.</p>
        {% endif %}

        <form action="{% url 'polls:create_task' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>Criar Task</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <label for="title">Title: </label>
            <input id="title" type="text" name="title"  maxlength="100" required>

            <label for="description">Description: </label>
            <input id="description" type="text" name="description" required>

        </fieldset>
        <input type="submit" value="Criar Task">
        </form>
    </body>
</html>

polls/templates/polls/task.html
<!DOCTYPE html>
<html>
    <body>
        <p><b>{{ task.title }}:</b> {{ task.description }}</p>
        <p><b>Criação:</b> {{ task.pub_date }}</p>
        <form action="{% url 'polls:all_tasks' %}">
            <input type="submit"  value="Voltar">
        </form>

        <form action="{% url 'polls:delete_task' task.id %}", method="post">
            {% csrf_token %}
            <input id='id-submit' type='hidden' name = 'task_id' value = {{ task.id }}>
            <input type="submit" value="Deletar Task">
        </form>
    </body>
</html>